# Use a Node.js base image
FROM node:18

# Set working directory in the container
WORKDIR /app

# Copy package.json files from backend/api directory
COPY api/package*.json ./

# Install dependencies
RUN npm install

RUN npm rebuild bcrypt --build-from-source



# Copy the entire api directory
COPY api/ ./

# Expose backend port
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]